name: todo-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-todo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: API Tests
        working-directory: ./src/webapp/api
        run: |
          npm ci
          npm run test
